### ISSUE TITLE
Add instructions for running the demo

### ISSUE THREAD

**Issue by andheiberg** [chemisus/graphql#17]
I liked some of the idea's you've expressed, but would like to get a better handle in the practical implications. I tried running your demo with no luck.

I would have assumed that below would be sufficient to see something meaningful:

```
php -S localhost:5000 src/demo/main.php
```

This returns an exception.

<img width="1046" alt="screenshot 2018-02-26 14 42 32" src="https://user-images.githubusercontent.com/820962/36676335-4c8f9126-1b03-11e8-80d3-210a3f28dffb.png">

**Comment by chemisus** [comment]
Sorry for taking so long to respond, must have missed the email for the issue. I will take a look when I get a chance.

**Comment by chemisus** [comment]
The source that is in the demo appears to be a left over string I was using to test a parser I have been working on. 

I will update the demo.php page to server as a better demo.

**Comment by chemisus** [comment]
@andheiberg please see https://github.com/chemisus/graphql/blob/master/src/demo/main.php for an updated demo.
